[package]
name = "ml"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.7"
scraper = "0.20.0"
serde = {version = "1.0.210", features = ["serde_derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
